In [47]:
#Writing KNN classifier
import random
from scipy.spatial import distance

def euc(a,b):
    return distance.euclidean(a,b)

class scrappyknn():
    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train
    
    def predict(self,X_test):
        pred = []
        for row in X_test:
            #label = random.choice(self.y_train)
            label = self.closest(row) #k=1
            pred.append(label)
        return pred
    
    def closest(self, row):
        best_distance = euc(row, self.X_train[0])
        best_index = 0
        for i in range(1, len(self.X_train)):
            dist = euc(row, self.X_train[i])
            if dist < best_distance:
                best_distance = dist
                best_index = i
        return self.y_train[best_index]

In [48]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn import tree

iris =load_iris()
print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0


In [49]:
X= iris.data
y = iris.target

In [50]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.5)
print(X_test)

[[5.7 3.8 1.7 0.3]
 [5.2 3.4 1.4 0.2]
 [6.9 3.2 5.7 2.3]
 [6.6 2.9 4.6 1.3]
 [4.5 2.3 1.3 0.3]
 [5.5 2.4 3.7 1. ]
 [5.  3.4 1.6 0.4]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.6 2.7 4.2 1.3]
 [4.6 3.2 1.4 0.2]
 [6.9 3.1 4.9 1.5]
 [7.1 3.  5.9 2.1]
 [5.4 3.  4.5 1.5]
 [5.9 3.  5.1 1.8]
 [5.4 3.7 1.5 0.2]
 [6.4 2.8 5.6 2.1]
 [6.2 3.4 5.4 2.3]
 [4.8 3.4 1.6 0.2]
 [6.8 3.  5.5 2.1]
 [6.1 2.9 4.7 1.4]
 [5.  3.5 1.6 0.6]
 [6.1 3.  4.6 1.4]
 [6.3 2.5 4.9 1.5]
 [6.3 2.5 5.  1.9]
 [5.1 3.3 1.7 0.5]
 [6.4 2.9 4.3 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.8 4.1 1.3]
 [5.7 4.4 1.5 0.4]
 [6.7 3.3 5.7 2.5]
 [5.4 3.4 1.5 0.4]
 [4.6 3.4 1.4 0.3]
 [5.6 2.8 4.9 2. ]
 [5.  3.5 1.3 0.3]
 [5.  3.  1.6 0.2]
 [5.5 2.4 3.8 1.1]
 [6.1 2.8 4.7 1.2]
 [5.8 2.8 5.1 2.4]
 [5.5 3.5 1.3 0.2]
 [4.3 3.  1.1 0.1]
 [4.6 3.6 1.  0.2]
 [4.8 3.1 1.6 0.2]
 [6.1 2.8 4.  1.3]
 [5.8 2.7 5.1 1.9]
 [5.  3.2 1.2 0.2]
 [4.7 3.2 1.3 0.2]
 [5.7 2.8 4.5 1.3]
 [4.8 3.4 1.9 0.2]
 [5.6 3.  4.1 1.3]
 [5.3 3.7 1.5 0.2]
 [6.7 3.1 4.4 1.4]
 [5.7 2.6 3.

In [51]:
#Training decsison tree
clf = scrappyknn()
clf.fit(X_train, y_train)
print(clf)

In [52]:
predictions = clf.predict(X_test)
print(predictions)

[0, 0, 2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 0, 2, 1, 0, 1, 2, 2, 0, 1, 1, 1, 0, 2, 0, 0, 2, 0, 0, 1, 1, 2, 0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 2, 2, 1, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2, 1]


In [53]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))

0.96
